name: I'm a Zensical team member
description: Only Zensical team members are allowed to create backlog items
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: >-
        ⚠️ Only Zensical team members are allowed to create backlog items. If you are not a Zensical team member, please do not use this template. Instead, vote on or comment in our public issue tracker. Submitting this issue as a non-team member will result in the backlog item being deleted. Repeated or deliberate attempts to bypass this policy may lead to temporary or permanent blocking from all Zensical projects to protect the project's workflow and contributors.
      description: >-
        Our process is documented [here](https://zensical.org/docs/community/how-we-work/).
    validations:
      required: true
